version: '3'
volumes:
  grafana-storage:
  prometheus:
services:
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/prometheus-data/prometheus.yml"]
    volumes:
      - ./prometheus-data:/prometheus-data
      - prometheus:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379