global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

- job_name: aula
  static_configs:
  - targets:
    - 3.238.78.104:80

- job_name: node
  static_configs:
  - targets: 
    - localhost:9100

- job_name: cadvisor
  static_configs:
  - targets:
    - 34.200.219.169:8081
